const __ws_styles_WorkspaceBrowser_module = {
  clearButton: "dshuiw_b77d1a_clearButton",
  deleteAction: "dshuiw_b77d1a_deleteAction",
  deleteStatus: "dshuiw_b77d1a_deleteStatus",
  empty: "dshuiw_b77d1a_empty",
  fade: "dshuiw_b77d1a_fade",
  flatList: "dshuiw_b77d1a_flatList",
  groupSection: "dshuiw_b77d1a_groupSection",
  headerActions: "dshuiw_b77d1a_headerActions",
  headerActionsHidden: "dshuiw_b77d1a_headerActionsHidden",
  iconButton: "dshuiw_b77d1a_iconButton",
  list: "dshuiw_b77d1a_list",
  listArea: "dshuiw_b77d1a_listArea",
  listTopDropActive: "dshuiw_b77d1a_listTopDropActive",
  listTopDropIndicator: "dshuiw_b77d1a_listTopDropIndicator",
  rail: "dshuiw_b77d1a_rail",
  renameError: "dshuiw_b77d1a_renameError",
  renameInput: "dshuiw_b77d1a_renameInput",
  root: "dshuiw_b77d1a_root",
  search: "dshuiw_b77d1a_search",
  searchButton: "dshuiw_b77d1a_searchButton",
  searchExpanded: "dshuiw_b77d1a_searchExpanded",
  searchInput: "dshuiw_b77d1a_searchInput",
  searchSlot: "dshuiw_b77d1a_searchSlot",
  searchSlotExpanded: "dshuiw_b77d1a_searchSlotExpanded",
  searchStatus: "dshuiw_b77d1a_searchStatus",
  searchTree: "dshuiw_b77d1a_searchTree",
  searchWarning: "dshuiw_b77d1a_searchWarning",
  sectionHeader: "dshuiw_b77d1a_sectionHeader",
  sectionLabel: "dshuiw_b77d1a_sectionLabel",
  sectionLabelHidden: "dshuiw_b77d1a_sectionLabelHidden",
  sessionOverflowButton: "dshuiw_b77d1a_sessionOverflowButton",
  treeBody: "dshuiw_b77d1a_treeBody",
  wide: "dshuiw_b77d1a_wide",
  workspaceDropAfter: "dshuiw_b77d1a_workspaceDropAfter",
  workspaceDropBefore: "dshuiw_b77d1a_workspaceDropBefore",
} as const;
export default __ws_styles_WorkspaceBrowser_module;
