const __ws_styles_Rows_module = {
  arrow: "dshuiw_e1cab6_arrow",
  arrowOpen: "dshuiw_e1cab6_arrowOpen",
  chevron: "dshuiw_e1cab6_chevron",
  dot: "dshuiw_e1cab6_dot",
  dropAfter: "dshuiw_e1cab6_dropAfter",
  dropBefore: "dshuiw_e1cab6_dropBefore",
  flatSessionRowWithoutStatus: "dshuiw_e1cab6_flatSessionRowWithoutStatus",
  folder: "dshuiw_e1cab6_folder",
  folderActive: "dshuiw_e1cab6_folderActive",
  hoverContent: "dshuiw_e1cab6_hoverContent",
  hoverPath: "dshuiw_e1cab6_hoverPath",
  hoverStatus: "dshuiw_e1cab6_hoverStatus",
  hoverTime: "dshuiw_e1cab6_hoverTime",
  hoverTitle: "dshuiw_e1cab6_hoverTitle",
  iconButton: "dshuiw_e1cab6_iconButton",
  menuOpen: "dshuiw_e1cab6_menuOpen",
  meta: "dshuiw_e1cab6_meta",
  projectRow: "dshuiw_e1cab6_projectRow",
  projectText: "dshuiw_e1cab6_projectText",
  renameInput: "dshuiw_e1cab6_renameInput",
  rowActions: "dshuiw_e1cab6_rowActions",
  searchResultHeading: "dshuiw_e1cab6_searchResultHeading",
  searchResultMeta: "dshuiw_e1cab6_searchResultMeta",
  searchResultRow: "dshuiw_e1cab6_searchResultRow",
  searchResultSnippet: "dshuiw_e1cab6_searchResultSnippet",
  searchResultTitle: "dshuiw_e1cab6_searchResultTitle",
  searchResultWorkspace: "dshuiw_e1cab6_searchResultWorkspace",
  selected: "dshuiw_e1cab6_selected",
  sessionRow: "dshuiw_e1cab6_sessionRow",
  slot: "dshuiw_e1cab6_slot",
  time: "dshuiw_e1cab6_time",
  title: "dshuiw_e1cab6_title",
  visuallyHidden: "dshuiw_e1cab6_visuallyHidden",
} as const;
export default __ws_styles_Rows_module;
